### ISSUE TITLE
Collision with ground

### ISSUE THREAD

**Issue by jrieffel** [voxcraft/voxcraft-sim#20] opened 2020-07-06 19:02 UTC
In the voxcraft-viz sandbox, I'm pretty sure I have the physics settings correct, but even with low time-steps the robots seems to penetrate the ground slightly.  Am I missing a setting?

![image](https://user-images.githubusercontent.com/6656810/86629632-b5401a00-bf99-11ea-822c-5483a6e14e99.png)

**Comment by skriegman** [comment] 2020-07-06 19:19
This is simply an artifact of how the voxels are drawn in voxcraft-viz when they are smushed against the ground due to their softness and the weight of the overall robot. Remember: there are no voxels. Not in in the simulation anyway. There are only beams between masses, and springs against the ground. These interacting elements could represent, and be drawn as, discrete voxels or spheres, or with a smooth mesh generated via marching cubes. If this bothers you aesthetically, it might be easier to modify the appearance in Unity. We provide an example of this [here](https://voxcraft.github.io/design#unity).

**Comment by liusida** [comment] 2020-07-06 19:22
Sorry about the slight penetration. Haha. maybe next time we should draw a thicker "floor" and disable watching the robot from "underground".

**Comment by jrieffel** [comment] 2020-07-06 19:27
Thanks. In an unrelated note, sometimes my robots flip over and then the simulation becomes unstable. Is there a relation? It's hard to imagine that the model cares which way up is.

(I can provide a model of you'd like to replicate)

jr

**Comment by liusida** [comment] 2020-07-06 19:28
could you take a picture of the "unstable" scene? So we can diagnose and come up with some potential explanations.

**Comment by skriegman** [comment] 2020-07-10 23:50
I'm closing this thread about how the sim is drawn. @jrieffel please submit another issue with the materials needed to reproduce your unstable simulation.

**Closed as completed by skriegman** 2020-07-10 23:50 UTC
Labels: invalid
